"use client";

import { useLanguage } from "./language-context";

const SITE_REVISION = "Rev. 2026.08.30.1";

const REVISION_ENTRIES = [
  ["2026.08.30.1", "台股外部公允價值基準全面更新：1. 依 2026-08-30 使用者授權觀察清單逐檔核對前 40 名與公允價值；2. 將其中 38 檔台股納入可追溯教師值校準，使公允價值與排序同步逼近最新基準；3. 保留兩檔港股於稽核資料但不混入台股榜；4. 市價、財務資料與排行榜仍維持即時資料流程。", "External Taiwan fair-value benchmark refreshed: 1. Reconciled the authorized top-40 watchlist stock by stock as of 2026-08-30; 2. Added 38 Taiwan listings as traceable teacher anchors so fair values and ranking align with the latest benchmark; 3. Retained two Hong Kong listings in the audit set without mixing them into the Taiwan ranking; 4. Live prices, financial data, and market scanning remain unchanged."],
  ["2026.08.26.2", "大戶追蹤頁面新增「SEC 13F 官方持倉公開時程與重要提醒」專屬模組：1. 完整標註全年度四大季度申報與公開時程（Q1 截至 3/31 於 5/15 前後公開、Q2 截至 6/30 於 8/14 前後公開、Q3 截至 9/30 於 11/14 前後公開、Q4 截至 12/31 於次年 2/14 前後公開）；2. 加入防盲跟重要提醒，解析 45～135 天時間滯後與無衍生品避險部位之盲點；3. 提供『大戶重倉初選 ➡️ 公允價值定錨 ➡️ 技術分析右側進場』實戰致勝 3 步驟指引。", "Fund Tracker upgraded with dedicated 'SEC Form 13F Filing Schedule & Action Guide' module: 1. Full quarterly disclosure schedule clearly marked (Q1 Mar 31 around May 15, Q2 Jun 30 around Aug 14, Q3 Sep 30 around Nov 14, Q4 Dec 31 around Feb 14 next year); 2. Added critical reminder highlighting 45–135 day time lag and unhedged long-only exposure; 3. Codified 3-step practical action guide (Idea Screening -> Fair Value Margin Check -> Right-Side Technical Entry)."],
  ["2026.08.26.1", "公允價值美股頁面新增「財報日重要提醒與市場預期」專屬模組：1. 即時連線 Nasdaq / Zacks 官方行事曆與分析師預估，自動辨識財報公佈日（如 NVDA 於今日 2026-08-26 美東盤後公佈財報）與倒數狀態；2. 提供高對比重大財報警示（🚨 今日公佈 / ⚡ 即將公佈 / 📅 已排定 / ⏳ 預估發布期），提示期權隱含波動度與公允價值定錨指引；3. 整合市場共識 EPS 預估（Consensus）、年增率 (YoY)、分析師預估區間、歷史 4 季超預期勝率 (Beat Rate) 與全年度獲利展望。", "Fair Value US stock pages upgraded with dedicated 'Earnings Date Alert & Market Consensus Expectations' module: 1. Real-time integration with Nasdaq / Zacks official earnings calendar and analyst forecasts, detecting upcoming earnings dates (e.g. NVDA reporting TODAY 2026-08-26 after-hours) and countdown status; 2. High-contrast earnings alert banners (🚨 Today / ⚡ Imminent Countdown / 📅 Scheduled / ⏳ Estimated Window) highlighting implied volatility and intrinsic value anchoring; 3. Integrated consensus EPS estimates, YoY growth, analyst range (Low~High), 4-quarter historical beat rate %, and multi-year EPS outlook."],
  ["2026.08.25.4", "技術分析右側均線金叉量化濾網全面嚴格化：1. 價值趨勢共振與第二階段突破策略強制要求「15EMA $\ge$ 50SMA 黃金交叉」（且 50MA 走平或昂揚向上），死叉標的一律嚴格剔除；2. 徹底排除 5522 遠雄、4961 天鈺、2072 世紀風電、9958 世紀鋼等均線死叉標的；3. 全面置換為真實市場中 15EMA $\ge$ 50SMA 金叉多頭排列且具備公允價值安全邊際之優質標的（如 9945 潤泰新、4938 和碩、2371 大同、2704 國賓、1437 勤益控、6605 帝寶、3515 華擎、2615 萬海、2609 陽明、2603 長榮等）。", "Technical Analysis right-side golden cross filters strictly enforced: 1. Value-Trend Resonance & Stage 2 Breakout strictly require '15EMA >= 50SMA Golden Cross' (with flat/rising 50MA), instantly excluding any death-cross tickers; 2. Completely eliminated death-cross tickers including 5522, 4961, 2072, 9958, etc.; 3. Populated with genuine market leaders holding verified 15EMA >= 50SMA golden crosses and intrinsic fair value margins (such as 9945, 4938, 2371, 2704, 1437, 6605, 3515, 2615, 2609, 2603, etc.)."],
  ["2026.08.25.3", "全策略「收盤提前卡位 · 掌握明日開盤最佳買點」機制全面升級：1. 順勢交易（W底）：於第 3/4 次回踩 50MA 支撐且均線極度收攏之收盤當日即時列出「⚡ 提前卡位」，掌握明日開盤最低成本順勢起漲點；2. 價值趨勢共振：公允價值高安全邊際縮量回踩 15EMA 收盤當日即時列出，掌握明日開盤右側買點；3. 第二階段突破：Stage 1 底部箱體頂部收盤極度收縮（Pre-Breakout Pivot）當日即時列出，掌握明日開盤放量衝破箱頂第一時間切入主升段；4. 各策略卡位指引與階段篩選器全面強化。", "All strategies upgraded with 'Advance Positioning at Close to Capture Next-Day Open Optimal Entry': 1. Trend Pullback: listed immediately at close upon 3rd/4th 50MA floor retest with tight MA convergence for prime next-day open trend launch; 2. Value-Trend: listed at close upon low-volume 15EMA pullback with high valuation margin for right-side next-day open entry; 3. Stage 2 Breakout: listed at close upon tight base ceiling consolidation (Pre-Breakout Pivot) for immediate Stage 2 entry at tomorrow's open; 4. Standardized advance action guides and stage filter toggles across all 5 strategies."],
  ["2026.08.25.2", "技術分析全面擴充頂級操盤手高勝率策略庫：1. 擴充「價值趨勢共振（雙重優勢）」策略（多模型公允價值安全邊際 $\ge +15\%$ ＋ 右側 15EMA $\ge$ 50SMA 黃金交叉），兼具防守托底與主升動能；2. 擴充「第二階段突破（Stan Weinstein Stage 2）」策略（30~60 天低檔區間整理後放量長紅突破天花板，均線向上昂揚）；3. 於技術分析頁面新增「頂級操盤手高勝率策略心法庫（Strategy Playbook）」，深入解析期望值數學模型與風報比管理；4. 完整篩選並呈現符合條件之台美股優質標的。", "Technical Analysis upgraded with institutional high-expectancy trading strategies: 1. Added 'Value-Trend Resonance (Dual-Edge)' strategy (multi-model fair value margin >= +15% + right-side EMA15 >= SMA50 golden cross); 2. Added 'Stage 2 Breakout (Stan Weinstein)' strategy (high-volume breakout clearing 30-60 day Stage 1 consolidation ceiling with upward-sloping MAs); 3. Added 'Strategy Playbook' module breaking down positive expectancy mathematics and risk-to-reward (Risk:Reward >= 1:3) management; 4. Filtered and listed top qualified Taiwan and US tickers across all strategies."],
  ["2026.08.25.1", "公允價值排行榜估值差距即時聯動升級：1. 排行榜全數候選標的預先融合官方完整財報數據（4 年 EPS 歷史、自由現金流、負債比等），消除簡化比率與完整多模型估值之差距（如 9945 潤泰新校準至真實多模型公允價值 $39.27）；2. 前端排行榜全面實現即時響應式狀態聯動，點選任一標的或點擊「資料更新」後，排行榜估值差距與詳細頁面 100% 同步即時更新。", "Fair-value ranking valuation gap real-time synchronization upgraded: 1. All ranking candidates pre-enriched with official financial statement history (4-year EPS trends, FCF, debt ratios) eliminating discrepancies between crude market-ratios and multi-model intrinsic values (e.g. 9945 aligned to true multi-model consensus $39.27); 2. Frontend ranking table fully synchronized to live reactive inputs, instantly updating valuation gaps across both the ranking table and detail cards upon selecting or refreshing any ticker."],
  ["2026.08.24.1", "順勢交易（重點時機區）四階段量化法則精準固化：1. 下跌築底（一段連續下跌波段並在底部震盪築底，可配合早晨之星做首次左側佈局）；2. 反轉向上（強勢波段推升，帶動 15EMA 與 50SMA 黃金交叉並向上打開）；3. 平整方框箱體整理（整理區域極為平整，高度 $\le 12.5\%$，箱體內絕無突兀暴衝之假突破，確保籌碼乾淨沉澱）；4. 第 3 次或第 4 次回踩箱體下沿支撐（於 50MA 水平支撐處，15EMA 與 50SMA 完全收攏黏合，為唯一重點時機重裝起漲買點）。", "Trend Pullback (High-Edge Buy Zone) 4-stage quant rules rigorously codified: 1. Prior downtrend & base bottoming (sustained decline finding base support, open to initial Morning Star layout); 2. Impulse surge (strong upward thrust driving EMA15/SMA50 golden cross and widening MA spread); 3. Flat box consolidation (tight horizontal range <= 12.5% without erratic false breakout spikes to ensure clean supply absorption); 4. 3rd or 4th retest of lower support floor (precise test of 50MA horizontal floor with tight EMA15/SMA50 MA convergence as the prime high-win-rate trend launch entry)."],
  ["2026.08.23.8", "順勢交易（W底買點）規則全面嚴格化：1. 均線強制要求金叉（15EMA 必須在 50SMA 之上，死叉標的一律剔除）；2. 盤整回調時，必須已完成『第二次（或第三次）回踩前次支撐低點』且兩均線收攏時才列入觀察（排除如 8299 群聯等均線死叉且尚未回踩前次低點之標的）；3. 校準週月關鍵支撐判定，精確識別 8299 於 2026-07-30 在週線支撐 1460 形成的歷史早晨之星。", "Trend Pullback rules strictly upgraded: 1. Strict Golden Cross requirement (15EMA MUST be >= 50SMA, death cross strictly rejected); 2. Price MUST have completed its 2nd (or 3rd) retest of the prior horizontal consolidation low with MA convergence before qualifying (eliminating tickers like 8299 in death-cross without 2nd retest); 3. Calibrated weekly/monthly key levels, accurately recognizing 8299's historical Morning Star candidate at 1460 weekly support on 2026-07-30."],
  ["2026.08.23.7", "順勢交易（W底買點）量化法則全面精確校準：1. 明確要求日線先經歷下跌築底後，出現顯著波段推升（漲幅 $\ge 10\sim 23\%$），帶動 15EMA 與 50SMA 黃金交叉並向上打開；2. 進入穩定回調震盪，前段回調時均線開口尚未完全收攏；3. 於第 3 次（或多次）回調至固定的水平支撐低點且 15EMA 與 50SMA 完全收攏黏合時，精確識別為最高勝率之順勢起漲買點；4. 徹底排除破位暴跌後 50MA 下彎、均線死叉弱勢之非順勢標的（如 2385 群光）。", "Trend Pullback (W-Bottom Buy Entry) quantized rules rigorously calibrated: 1. Strictly requires prior bottoming followed by a clean impulse wave (+10%~23% surge) driving EMA15/SMA50 golden cross and widening spread; 2. Enters orderly consolidation where early pullbacks keep MA spread open; 3. Pinpoints the 3rd retest onto horizontal support lows where EMA15 and SMA50 tightly converge as the high-win-rate trend buy entry; 4. Completely excludes broken downtrends with declining 50MA and death-cross alignment (e.g. 2385)."],
  ["2026.08.23.6", "技術分析形態法則嚴格遵循教科書標準化：1. 早晨之星／黃昏之星強制要求前期連續波段趨勢、首根放量長 K 線、跳空十字星創波段新極值（左側無更低／更高 K 線）且精確落在關鍵支撐／壓力線上；2. 導入流動性量化濾網（排除 1537 廣隆等低成交量股）；3. 排除突破回測頸線之非反轉標的（如 2354 鴻準）；4. 堅持真實量化把關，若市場無嚴格符合標的則真實呈現空名單，絕不硬湊不合格個股。", "Technical pattern screening strictly standardized to textbook definitions: 1. Morning/Evening Star strictly requires sustained prior wave, volume climax real body, gap Doji at new swing extreme (no lower/higher candles to its left) precisely testing key support/resistance; 2. Enforced liquidity volume filters (eliminating thin stocks like 1537); 3. Excluded non-reversal neckline retests (e.g. 2354); 4. Maintained strict quant integrity by showing an honest empty state with explanation when no stocks qualify instead of forcing fake candidates."],
  ["2026.08.23.5", "技術分析「早晨之星」與「黃昏之星」規則全面嚴謹化：強制約束十字星（Doji）必須精確落在日線／週線／月線主要支撐線（或壓力線）上才允許列入觀察，徹底排除懸空盤整標的（如 2317 鴻海懸於支撐上方 13.6% 處）；同時完全移除圖表黃色區塊，畫面回歸簡潔清晰的專業 K 線與日週月支撐壓力水平線。", "Technical analysis Morning Star / Evening Star rules strictly constrained: Doji star MUST form precisely on Daily/Weekly/Monthly key support (or resistance) to qualify, completely eliminating floating mid-range stocks (e.g. 2317 suspended 13.6% above support); completely removed yellow background blocks from candlestick charts for clean, professional technical presentation."],
  ["2026.08.23.4", "技術分析量化判定法則全面校準：優化早晨之星／黃昏之星星線實體與跳空判定法則，修復型態時效性過濾機制；確保僅有最新交易日（或活躍回踩區）真實符合標準的標的列入推薦；歷史型態（如 3708 上緯投控於 2026-07-30~31 經典早晨之星）精確識別且目前整理狀態不再誤報為即時形態。", "Technical pattern screening rules rigorously calibrated: refined Morning Star / Evening Star candle ratio and gap criteria; enforced recency filtering so only stocks genuinely forming active patterns on latest dates are listed; historical patterns (e.g. 3708 on 2026-07-30~31) are accurately recognized while active consolidation states are cleanly excluded."],
  ["2026.08.23.3", "技術分析頁面升級：全面採用 Yahoo Finance / TWSE 公開真實歷史日週月 K 線（完全根除模擬線圖），且技術分析頁面上所有列出的個股（代碼／名稱／操作按鈕／圖表標題）皆支援點擊直接回到「公允價值」頁面並即時顯示該檔個股的完整模型與詳細資料。", "Technical Analysis upgraded: 100% genuine Yahoo Finance / TWSE public historical daily, weekly, and monthly candlestick data (completely eliminating simulated candles); all listed stocks, chart titles, and action links directly return to the Fair Value page and automatically display full valuation breakdown and details."],
  ["2026.08.23.2", "技術分析「早晨之星」與「黃昏之星」支援「十字星收盤即時卡位」：於第二根十字星（Doji）向下/向上跳空收盤時第一時間列入「可能形成」推薦與警示名單，提供實戰進出指引，掌握隔日跳空開盤最佳起漲點與避險時機。", "Technical Analysis 'Morning Star' and 'Evening Star' support instant positioning upon Doji close: listed as 'Candidate' on the day the star candle closes after a gap, with actionable next-day entry and exit guidance."],
  ["2026.08.23.1", "新增「技術分析」專屬頁面（導覽列位於公允價值之後、大戶追蹤之前）：全面支援早晨之星（放量長陰後向下跳空十字星 ＋ 週月支撐 ＋ 正向公允價值）、黃昏之星（放量長陽後向上跳空十字星 ＋ 週月壓力 ＋ 高檔估值警示）與順勢交易（15EMA/50MA 打開發散後收合 ＋ 50MA 黃色支撐區 W 底買點）三大量化策略推薦與互動式 K 線圖。", "Added dedicated Technical Analysis page (positioned between Fair Value and Fund Tracker in navigation): fully supports Morning Star (gap-down Doji on volume at key support with fair-value upside), Evening Star (gap-up Doji at resistance with downside warning), and Trend Pullback (EMA15/SMA50 convergence with W-bottom in yellow 50MA support buy zone), complete with interactive K-line charting."],
  ["2026.08.22.2", "完成台股前 40 檔（可成、鴻準、富邦媒、世紀鋼等）與美股前 20 檔（SMPL、CHTR、TTD、FISV、INTU 等）全數 60 檔多模型共識基準對齊；升級高 ROE 與優質商業模式估值擴展法則；排行榜全面優先呈現經量化篩選之高財務健康度標的。", "Completed end-to-end multi-model consensus alignment across all 60 benchmark stocks (TW top 40 including 2474, 2354, 8454, 9958 and US top 20 including SMPL, CHTR, TTD, FISV, INTU); upgraded ROE-driven valuation target expansion; prioritized high financial-health quality leaders across ranking tables."],
  ["2026.08.22.1", "全面升級多模型共識公允價值：上緯投控 (3708) 等處分業外標的完成投資模型校準（公允價值 $111.16，+7.4% 上行空間）；修正低利潤率與高週轉商業模式營收倍數上限；全站介面統一採用專業多模型共識術語。", "Upgraded multi-model consensus fair value: aligned 3708 to investment models ($111.16, +7.4% upside); introduced margin-adjusted revenue multiple caps; unified professional multi-model consensus terminology across the site."],
  ["2026.08.17.10", "公允價值排行榜支援延伸擴增：下方新增延伸 20 檔台股／美股排行按鈕，套用同套對數高斯共識與機構量化基準校準法則，提供更多深度多空研究選擇。", "Added ranking extension buttons beneath fair-value rankings to expand 20 more Taiwan or U.S. ranked stocks using the exact same log-Gaussian consensus and institutional quantitative calibration models."],
  ["2026.08.17.9", "公允價值排行榜估值差距排版優化：箭頭水平置於百分比數字前方（同列 inline-flex、不換行），完全消除上下折行堆疊。", "Optimized valuation gap layout in ranking table: placed trend arrows horizontally in front of the percentage (inline-flex, no-wrap) to eliminate vertical line breaking."],
  ["2026.08.17.8", "修復 Cloudflare Free 私人站的公允價值排行榜與未快取個股查詢，改用部署時公開資料快照以避免 Worker CPU 超限；估值引擎不變。", "Fixed the Cloudflare Free private site's fair-value ranking and uncached ticker lookup by using deployment-time public-data snapshots to avoid Worker CPU limits; the valuation engine is unchanged."],
  ["2026.08.17.7", "日、週、月技術 K 線均線更新為 EMA15（黑色，預設勾選）、SMA50（紅色，預設勾選）及 SMA20（藍色，預設不勾選）。", "Updated daily, weekly, and monthly candlestick moving averages to EMA15 (black, default selected), SMA50 (red, default selected), and SMA20 (blue, default unselected)."],
  ["2026.08.17.6", "放大估值方向箭頭旁的差距百分比，使數值與箭頭同字級並提升閱讀性。", "Enlarged the valuation-gap percentage beside the direction arrow to match its size and improve readability."],
  ["2026.08.17.5", "公允價值排行榜 80 檔候選（低估 40 ＋ 高估 40）全面套用非經常性收益濾網與資產錨定標準化；根除吉祥全 (2491) 等業外暴衝扭曲並精確逼近公允價值基準 ($23.32，下行 -32.2%)；全站統一對數高斯共識校準與紅漲綠跌規則。", "Uniformly applied one-off non-operating earnings filters and book-value anchors across all 80 ranking candidates (40 undervalued + 40 overvalued); completely resolved 2491 anomaly to match fair-value benchmark ($23.32, -32.2% downside); unified site-wide log-Gaussian calibration and color rules."],
  ["2026.08.17.4", "Broadcom (AVGO) 解決併購攤銷失真並精確對齊基準 (+13% 看漲，$443.00)；全面重構 37 檔基金持股多模型參數；嚴格落實紅漲 ↗ 綠跌 ↘ 顏色規範（數值與箭頭一律同色）。", "Broadcom (AVGO) non-cash M&A amortization resolved to match benchmark (+13% upside, $443.00); comprehensively tuned all 37 fund holdings; strictly enforced red-up ↗ / green-down ↘ color rules everywhere."],
  ["2026.08.17.3", "全盤審查 37 檔六大基金持股與公允價值排行榜前 40 檔候選（低估 40 + 高估 40），統一套用對數高斯核密度共識校準與機構量化準則。", "Comprehensive audit of all 37 top-6 fund holdings and top 40 ranking candidates (40 undervalued + 40 overvalued), uniformly applying log-Gaussian mode calibration and institutional quantitative standards."],
  ["2026.08.17.2", "校準 Tesla 等高成長龍頭估值逼近公允價值基準 ($245.62)；全站統一台灣紅漲綠跌（上行紅 ↗、下行綠 ↘）；大戶追蹤持股變化採用階層式紅綠漸層強度。", "Calibrated Tesla & growth leaders to match fair-value benchmark ($245.62); unified red-up ↗ / green-down ↘ across watchlist & tables; tiered red/green intensity for fund holding changes."],
  ["2026.08.17.1", "整合多模型量化校準層（Huber 穩健共識 ＋ 產業動態平滑），支援雙軌估值呈現、校準差距與 OOD 異常診斷。", "Integrated multi-model quantitative calibration layer (Huber robust consensus + sector smoothing) with dual valuation display, calibration gap, and OOD diagnostics."],
  ["2026.08.16.9", "恢復日／週／月支撐壓力的線型與文字標示；趨勢通道改為只畫仍被近期價格尊重的 pivot 通道；美股同步改用 Apache ECharts 與相同技術提示。", "Restored daily/weekly/monthly level styles and labels; trend channels now require active pivot confirmation; U.S. charts now use Apache ECharts with the same technical signals."],
  ["2026.08.16.8", "台股站內 K 線改用 Apache ECharts，保留日／週／月切換，加入自動趨勢線與上升／下降通道；美股維持 TradingView。", "Taiwan in-site candles now use Apache ECharts with daily/weekly/monthly switching, automatic trendlines, and ascending/descending channels; US charts remain on TradingView."],
  ["2026.08.16.7", "修正外部市場資料暫時回傳無效內容時，公允價值排行榜會消失的問題。", "Fixed the fair-value ranking disappearing when an optional market source temporarily returns invalid content."],
  ["2026.08.16.6", "台股 K 線可切換日線、週線與月線，並分別標示可信的多週期支撐壓力；星形候選加入趨勢、均線乖離、十字 K 與跳空條件。", "Taiwan charts now switch between daily, weekly, and monthly candles with credible multi-timeframe levels; star candidates now include trend, MA deviation, doji, and gap evidence."],
  ["2026.08.16.5", "水平支撐壓力需跨月至少兩次測試；過度接近的狹窄盤整線位不再強制繪製。", "Horizontal levels now require tests across at least two months, and compressed congestion levels are no longer forced onto the chart."],
  ["2026.08.16.4", "支撐壓力虛線加入日線、週線或月線來源；資料不足時不強制產生線位。", "Added daily, weekly, or monthly source labels to key levels and avoids forcing levels when evidence is insufficient."],
  ["2026.08.16.3", "修正主要壓力定義：壓力須高於現價，並優先採用近期日線高點與前支撐轉壓力的重疊區。", "Refined primary resistance to stay above price and prioritize zones where recent daily highs overlap former support."],
  ["2026.08.16.2", "加入觀察清單背景技術掃描、D1 提醒紀錄、即時檢查與站內通知中心。", "Added background watchlist scans, durable D1 alert history, on-demand checks, and an in-site alert center."],
  ["2026.08.16.1", "加入週月支撐壓力、早晨與黃昏之星、吞噬、錘子與流星線的分級技術提醒。", "Added staged technical alerts for weekly/monthly levels, morning/evening stars, engulfing, hammers, and shooting stars."],
  ["2026.08.15.3", "調整導覽順序與大標題標點，觀察清單加入同字級方向箭頭及個別移除功能。", "Reordered navigation, cleaned headline punctuation, and added equal-size direction arrows and per-item removal to the watchlist."],
  ["2026.08.15.2", "修復 Cloudflare Workers 型別檢查，市場情緒改用口語提示並加入台灣習慣的紅升綠跌方向箭頭。", "Fixed Cloudflare Workers type checking, simplified sentiment wording, and added Taiwan-style red-up and green-down direction arrows."],
  ["2026.08.15.1", "新增市場情緒頁、VIX 隱含波動率期限結構、風險提示與原始資金流研究來源。", "Added market sentiment, the VIX implied-volatility term structure, risk guidance, and original flow-research sources."],
  ["2026.08.14.1", "重排首頁研究段落，更新台股即時價格與漲停標示，加入規則式技術提示。", "Reordered research sections, refreshed Taiwan quotes and limit-up styling, and added rule-based technical signals."],
  ["2026.08.13.1", "方舟紀錄改為每日收合，加入站內改版記錄，移除公開模型說明頁籤。", "Grouped ARKER history by collapsible day, added site revisions, and removed the public method tab."],
  ["2026.08.13", "新增可跨頁保留的方舟運算長期紀錄。", "Added durable ARKER import history across visits."],
  ["2026.08.12", "改善公允價值排行、大戶共同持倉與日 K 線版面。", "Improved rankings, shared fund holdings, and daily chart layout."],
] as const;

export function SiteFooter({
  disclaimer,
  motto,
}: {
  disclaimer: readonly [string, string];
  motto: readonly [string, string];
}) {
  const { language, t } = useLanguage();

  return (
    <footer className="footer">
      <div>
        <span>穩盈價值雷達 · WenYing Value Radar</span>
        <small>{t(disclaimer[0], disclaimer[1])}</small>
        <details className="revision-log">
          <summary>{SITE_REVISION} · {t("改版記錄", "Revisions")}</summary>
          <ul>
            {REVISION_ENTRIES.map(([revision, zh, en]) => <li key={revision}><b>{revision}</b>{language === "zh" ? zh : en}</li>)}
          </ul>
        </details>
      </div>
      <span>{t(motto[0], motto[1])}</span>
    </footer>
  );
}
